package rtk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static rtk.Aika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.23 19:45:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AikaTest {



  // Generated by ComTest BEGIN
  /** testParseToInt30 */
  @Test
  public void testParseToInt30() {    // Aika: 30
    assertEquals("From: Aika line: 31", 102590, parseToInt("01.42,59")); 
    assertEquals("From: Aika line: 32", 125340, parseToInt("02.05,34")); 
    assertEquals("From: Aika line: 33", 155350, parseToInt("02.35,35")); 
    assertEquals("From: Aika line: 34", 340280, parseToInt("05.40,28")); 
    assertEquals("From: Aika line: 35", 655350, parseToInt("10.55,35")); 
  } // Generated by ComTest END
}