package rtk.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import rtk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.07 21:50:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ErikoiskokeetTest {



  // Generated by ComTest BEGIN
  /** testErikoiskokeet16 */
  @Test
  public void testErikoiskokeet16() {    // Erikoiskokeet: 16
    Erikoiskokeet ekt = new Erikoiskokeet(); 
    Erikoiskoe ek1 = new Erikoiskoe(1, 1, "Ek1", 1, LocalDate.of(2020, 1, 1)); 
    Erikoiskoe ek2 = new Erikoiskoe(2, 1, "Ek2", 2, LocalDate.of(2020, 1, 1)); 
    Erikoiskoe ek3 = new Erikoiskoe(3, 2, "Ek3", 3, LocalDate.of(2020, 1, 1)); 
    Erikoiskoe ek4 = new Erikoiskoe(4, 3, "Ek4", 4, LocalDate.of(2020, 1, 1)); 
    Erikoiskoe ek5 = new Erikoiskoe(5, 2, "Ek5", 5, LocalDate.of(2020, 1, 1)); 
    Erikoiskoe ek6 = new Erikoiskoe(99, 2, "Ek6", 6, LocalDate.of(2020, 1, 1)); 
    ekt.lisaa(ek1); 
    ekt.lisaa(ek2); 
    ekt.lisaa(ek3); 
    ekt.lisaa(ek4); 
    ekt.lisaa(ek5); 
    assertEquals("From: Erikoiskokeet line: 32", "[Ek1, 1.0km, 2020-01-01, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, null, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
    ekt.lisaa(ek1); 
    assertEquals("From: Erikoiskokeet line: 34", "[Ek1, 1.0km, 2020-01-01, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, null, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
    ekt.muokkaa(ek1, new Erikoiskoe(0, 1, "Ek1Muokattu", 1.5, LocalDate.of(2020, 1, 1))); 
    assertEquals("From: Erikoiskokeet line: 36", "[Ek1Muokattu, 1.5km, 2020-01-01, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, null, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
    ekt.muokkaa(ek1, null); 
    assertEquals("From: Erikoiskokeet line: 38", "[Ek1Muokattu, 1.5km, 2020-01-01, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, null, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
    ekt.lisaaUusi(ek6); 
    assertEquals("From: Erikoiskokeet line: 40", "[Ek1Muokattu, 1.5km, 2020-01-01, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, Ek6, 6.0km, 2020-01-01, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
    ekt.poista(ek1); 
    assertEquals("From: Erikoiskokeet line: 42", "[null, Ek2, 2.0km, 2020-01-01, Ek3, 3.0km, 2020-01-01, Ek4, 4.0km, 2020-01-01, Ek5, 5.0km, 2020-01-01, Ek6, 6.0km, 2020-01-01, null, null, null, null]", Arrays.toString(ekt.getKaikki())); 
  } // Generated by ComTest END
}