package rtk.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import rtk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.07 22:48:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RallitTest {



  // Generated by ComTest BEGIN
  /** testRallit16 */
  @Test
  public void testRallit16() {    // Rallit: 16
    Rallit rallit = new Rallit(); 
    Ralli ralli1 = new Ralli(1, "Ralli1", "Paikka1", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    Ralli ralli2 = new Ralli(2, "Ralli2", "Paikka2", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    Ralli ralli3 = new Ralli(3, "Ralli3", "Paikka3", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    Ralli ralli4 = new Ralli(4, "Ralli4", "Paikka4", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    Ralli ralli5 = new Ralli(5, "Ralli5", "Paikka5", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    Ralli ralli6 = new Ralli(6, "Ralli6", "Paikka6", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1)); 
    rallit.lisaa(ralli1); 
    rallit.lisaa(ralli2); 
    rallit.lisaa(ralli3); 
    rallit.lisaa(ralli4); 
    rallit.lisaa(ralli5); 
    assertEquals("From: Rallit line: 32", "[Ralli1, 2020-01-01 - 2020-01-01, Ralli2, 2020-01-01 - 2020-01-01, Ralli3, 2020-01-01 - 2020-01-01, Ralli4, 2020-01-01 - 2020-01-01, Ralli5, 2020-01-01 - 2020-01-01]", Arrays.toString(rallit.getLista().toArray())); 
    rallit.lisaa(ralli1); 
    assertEquals("From: Rallit line: 34", "[Ralli1, 2020-01-01 - 2020-01-01, Ralli2, 2020-01-01 - 2020-01-01, Ralli3, 2020-01-01 - 2020-01-01, Ralli4, 2020-01-01 - 2020-01-01, Ralli5, 2020-01-01 - 2020-01-01]", Arrays.toString(rallit.getLista().toArray())); 
    rallit.muokkaa(ralli1, new Ralli(99, "Ralli1Muokattu", "Paikka1Muokattu", LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 1))); 
    assertEquals("From: Rallit line: 36", "[Ralli1Muokattu, 2020-01-01 - 2020-01-01, Ralli2, 2020-01-01 - 2020-01-01, Ralli3, 2020-01-01 - 2020-01-01, Ralli4, 2020-01-01 - 2020-01-01, Ralli5, 2020-01-01 - 2020-01-01]", Arrays.toString(rallit.getLista().toArray())); 
    rallit.muokkaa(ralli1, null); 
    assertEquals("From: Rallit line: 38", "[Ralli1Muokattu, 2020-01-01 - 2020-01-01, Ralli2, 2020-01-01 - 2020-01-01, Ralli3, 2020-01-01 - 2020-01-01, Ralli4, 2020-01-01 - 2020-01-01, Ralli5, 2020-01-01 - 2020-01-01]", Arrays.toString(rallit.getLista().toArray())); 
    rallit.poista(ralli2); 
    assertEquals("From: Rallit line: 40", "[Ralli1Muokattu, 2020-01-01 - 2020-01-01, Ralli3, 2020-01-01 - 2020-01-01, Ralli4, 2020-01-01 - 2020-01-01, Ralli5, 2020-01-01 - 2020-01-01]", Arrays.toString(rallit.getLista().toArray())); 
  } // Generated by ComTest END
}